language: php
php:
  - 7.2

before_install:
  - composer self-update
  - composer clear-cache

install:
  - travis_retry composer update --no-interaction --no-suggest --prefer-source --optimize-autoloader

script:
  - composer lint
  - phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  - email: false